#修改端口号
server:
  port: 8761
#eureka服务端名字
eureka:
  instance:
    hostname: eureka-server
  client:
    #由于自己就是服务器，不需要注册到自己
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false
    serviceUrl:
      #defaultZone: http://user:password@192.168.11.45:8761/eureka/
      dev: http://${eureka.instance.hostname}:${server.port}/eureka/
      prod: http://${eureka.instance.hostname}:${server.port}/eureka/
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/