#端口和tomcat相关配置
server:
  port: 8080
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: utf-8

#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aufine_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always

#mybatie配置
mybatis:
  mapper-locations: classpath*:mapper/*DAO.xml

#日志配置
logging:
  #file: E:\log\springboot.log
  file: log/springboot.log
  level:
    com.web.aufine.dao: INFO